### ISSUE TITLE
Radius feature

### ISSUE THREAD

**Issue by kheeres** [mapbox/geojson.io#597] opened 2018-02-26 15:54 UTC
You have a polygon and rectangle feature.  Is it possible you could add a circle radius feature.  What I have been looking for is a way to draw circles of set radius (example 10 miles, 20 miles) around a map point (say a city).  I could see doing a layer at 10 miles.  Another layer at 20 miles.  Another layer at 30 miles, etc.  Creating a bullseye map around a center map point.

Thanks.
Keith

**Comment by tomscholz** [comment] 2018-02-26 17:56
Duplicate of #537. Please search across open and closed issues first, before you open a new one.

**Comment by tomscholz** [comment] 2018-03-03 13:05
Please close

**Comment by bhousel** [comment] 2018-03-03 13:13
Hey @kheeres and @tomscholz 
I'd like to leave this open as a feature that we'd consider for a possible geojson.io refresh.  (yes #537 was closed but  that was mostly because there was no interest at the time).  

Thanks, and please feel free to open any other issues for ideas that would make working with geojson.io better - I'd like to hear them 👂

**Comment by kheeres** [comment] 2018-03-03 15:19
Hi.  Thanks.  Found a tool that will do it in Google Earth.  http://www.metzgerwillard.us/rings/rings.html.  Problem solved for me.

**Comment by kyoukhana** [comment] 2018-06-18 18:22
The feature is already done here

https://www.mapbox.com/labs/draw-circle/

**Comment by as-stack** [comment] 2020-04-17 20:18
http://geojson.io/#map=11/51.1785/4.4117

**Comment by as-stack** [comment] 2020-04-17 20:19
https://leafletjs.com/examples/geojson/

&

http://geojson.io/#map=11/51.1785/4.4117

**Closed** 2022-11-03 02:00 UTC
