### ISSUE TITLE
OCM map says "API Key Required" 

### ISSUE THREAD

**Issue by jidanni** [mapbox/geojson.io#601] opened 2018-03-01 12:15 UTC
I am browsing
http://geojson.io/#id=github:benbalter/dc-wifi-social/blob/master/bars.geojson&map=17/38.89787/-77.03696
and the OCM map says "API Key Required" on top of the map.

Choose OCM from the four buttons in the lower left.

**Comment by sgillies** [comment] 2018-03-01 14:46
This is a duplicate of #577.

**Closed by sgillies** 2018-03-01 14:46 UTC
Labels: wontfix
