### ISSUE TITLE
Working dataset layers not visible after switching to OSM style

### ISSUE THREAD

**Issue by ChrisFleet** [mapbox/geojson.io#740] opened 2022-10-24 17:36 UTC
This is a specific problem when a raster tile layer has been added, using 'Meta > Add raster tile layer'. An opened GeoJSON file which displays fine on top of the added raster tile layer, and displays fine on all the other layers, ie. 'Streets | Satellite Streets...' etc. disappears when the OSM layer is selected.

**Comment by chriswhong** [comment] 2022-10-24 18:00
I was able to reproduce this, it looks like `style.load` event is not firing but only on certain transitions (like from the OSM style to the user-defined raster style)

We listen for `style.load` after the user switches base styles, then we re-add the source and layers for the working geojson dataset.  https://github.com/mapbox/geojson.io/blob/gh-pages/src/ui/map/index.js#L205-L254

Instead of listening for the event we could probably just trigger this manually when the user clicks the button for one of the styles.

**Comment by chriswhong** [comment] 2022-11-07 01:45
Fixed in #751

**Closed by chriswhong** 2022-11-07 01:45 UTC
Labels: bug

**Comment by ChrisFleet** [comment] 2022-11-07 07:16
Many thanks @chriswhong - I've just tested this now, and you're quite right, its all sorted. Very grateful to you.
